// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ion/v1/daemon.proto

package ionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sund3RRR/ion/pkg/pb/ion/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DaemonServiceName is the fully-qualified name of the DaemonService service.
	DaemonServiceName = "ion.v1.DaemonService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DaemonServicePingProcedure is the fully-qualified name of the DaemonService's Ping RPC.
	DaemonServicePingProcedure = "/ion.v1.DaemonService/Ping"
	// DaemonServiceVersionProcedure is the fully-qualified name of the DaemonService's Version RPC.
	DaemonServiceVersionProcedure = "/ion.v1.DaemonService/Version"
)

// DaemonServiceClient is a client for the ion.v1.DaemonService service.
type DaemonServiceClient interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	Version(context.Context, *connect.Request[v1.VersionRequest]) (*connect.Response[v1.VersionResponse], error)
}

// NewDaemonServiceClient constructs a client for the ion.v1.DaemonService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDaemonServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DaemonServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	daemonServiceMethods := v1.File_ion_v1_daemon_proto.Services().ByName("DaemonService").Methods()
	return &daemonServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+DaemonServicePingProcedure,
			connect.WithSchema(daemonServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		version: connect.NewClient[v1.VersionRequest, v1.VersionResponse](
			httpClient,
			baseURL+DaemonServiceVersionProcedure,
			connect.WithSchema(daemonServiceMethods.ByName("Version")),
			connect.WithClientOptions(opts...),
		),
	}
}

// daemonServiceClient implements DaemonServiceClient.
type daemonServiceClient struct {
	ping    *connect.Client[v1.PingRequest, v1.PingResponse]
	version *connect.Client[v1.VersionRequest, v1.VersionResponse]
}

// Ping calls ion.v1.DaemonService.Ping.
func (c *daemonServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// Version calls ion.v1.DaemonService.Version.
func (c *daemonServiceClient) Version(ctx context.Context, req *connect.Request[v1.VersionRequest]) (*connect.Response[v1.VersionResponse], error) {
	return c.version.CallUnary(ctx, req)
}

// DaemonServiceHandler is an implementation of the ion.v1.DaemonService service.
type DaemonServiceHandler interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	Version(context.Context, *connect.Request[v1.VersionRequest]) (*connect.Response[v1.VersionResponse], error)
}

// NewDaemonServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDaemonServiceHandler(svc DaemonServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	daemonServiceMethods := v1.File_ion_v1_daemon_proto.Services().ByName("DaemonService").Methods()
	daemonServicePingHandler := connect.NewUnaryHandler(
		DaemonServicePingProcedure,
		svc.Ping,
		connect.WithSchema(daemonServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	daemonServiceVersionHandler := connect.NewUnaryHandler(
		DaemonServiceVersionProcedure,
		svc.Version,
		connect.WithSchema(daemonServiceMethods.ByName("Version")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ion.v1.DaemonService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DaemonServicePingProcedure:
			daemonServicePingHandler.ServeHTTP(w, r)
		case DaemonServiceVersionProcedure:
			daemonServiceVersionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDaemonServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDaemonServiceHandler struct{}

func (UnimplementedDaemonServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ion.v1.DaemonService.Ping is not implemented"))
}

func (UnimplementedDaemonServiceHandler) Version(context.Context, *connect.Request[v1.VersionRequest]) (*connect.Response[v1.VersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ion.v1.DaemonService.Version is not implemented"))
}
