// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    profile_package_id,
    executable,
    relative_path,
    materialized_path,
    store_path
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, profile_package_id, executable, relative_path, materialized_path, store_path, created_at
`

type CreateFileParams struct {
	ProfilePackageID int64  `json:"profile_package_id"`
	Executable       int64  `json:"executable"`
	RelativePath     string `json:"relative_path"`
	MaterializedPath string `json:"materialized_path"`
	StorePath        string `json:"store_path"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ProfilePackageID,
		arg.Executable,
		arg.RelativePath,
		arg.MaterializedPath,
		arg.StorePath,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProfilePackageID,
		&i.Executable,
		&i.RelativePath,
		&i.MaterializedPath,
		&i.StorePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFilesByProfilePackage = `-- name: DeleteFilesByProfilePackage :exec
DELETE FROM files
WHERE profile_package_id = ?
`

func (q *Queries) DeleteFilesByProfilePackage(ctx context.Context, profilePackageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFilesByProfilePackage, profilePackageID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, profile_package_id, executable, relative_path, materialized_path, store_path, created_at FROM files
WHERE id = ?
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProfilePackageID,
		&i.Executable,
		&i.RelativePath,
		&i.MaterializedPath,
		&i.StorePath,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByMaterializedPath = `-- name: GetFileByMaterializedPath :one
SELECT id, profile_package_id, executable, relative_path, materialized_path, store_path, created_at FROM files
WHERE materialized_path = ?
`

func (q *Queries) GetFileByMaterializedPath(ctx context.Context, materializedPath string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByMaterializedPath, materializedPath)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProfilePackageID,
		&i.Executable,
		&i.RelativePath,
		&i.MaterializedPath,
		&i.StorePath,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesByProfile = `-- name: ListFilesByProfile :many
SELECT files.id, files.profile_package_id, files.executable, files.relative_path, files.materialized_path, files.store_path, files.created_at FROM files
JOIN profile_packages ON profile_packages.id = files.profile_package_id
WHERE profile_packages.profile_id = ?
ORDER BY files.materialized_path
`

func (q *Queries) ListFilesByProfile(ctx context.Context, profileID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProfilePackageID,
			&i.Executable,
			&i.RelativePath,
			&i.MaterializedPath,
			&i.StorePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByProfilePackage = `-- name: ListFilesByProfilePackage :many
SELECT id, profile_package_id, executable, relative_path, materialized_path, store_path, created_at FROM files
WHERE profile_package_id = ?
ORDER BY relative_path
`

func (q *Queries) ListFilesByProfilePackage(ctx context.Context, profilePackageID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByProfilePackage, profilePackageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProfilePackageID,
			&i.Executable,
			&i.RelativePath,
			&i.MaterializedPath,
			&i.StorePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
