// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flakes.sql

package sqlc

import (
	"context"
)

const createFlake = `-- name: CreateFlake :one
INSERT INTO flakes (
    alias,
    flake_ref,
    lock_json,
    fingerprint
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, alias, flake_ref, lock_json, fingerprint, created_at
`

type CreateFlakeParams struct {
	Alias       string `json:"alias"`
	FlakeRef    string `json:"flake_ref"`
	LockJson    string `json:"lock_json"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) CreateFlake(ctx context.Context, arg CreateFlakeParams) (Flake, error) {
	row := q.db.QueryRowContext(ctx, createFlake,
		arg.Alias,
		arg.FlakeRef,
		arg.LockJson,
		arg.Fingerprint,
	)
	var i Flake
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.LockJson,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getFlake = `-- name: GetFlake :one
SELECT id, alias, flake_ref, lock_json, fingerprint, created_at FROM flakes
WHERE id = ?
`

func (q *Queries) GetFlake(ctx context.Context, id int64) (Flake, error) {
	row := q.db.QueryRowContext(ctx, getFlake, id)
	var i Flake
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.LockJson,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getFlakeByAliasFingerprint = `-- name: GetFlakeByAliasFingerprint :one
SELECT id, alias, flake_ref, lock_json, fingerprint, created_at FROM flakes
WHERE alias = ? AND fingerprint = ?
`

type GetFlakeByAliasFingerprintParams struct {
	Alias       string `json:"alias"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) GetFlakeByAliasFingerprint(ctx context.Context, arg GetFlakeByAliasFingerprintParams) (Flake, error) {
	row := q.db.QueryRowContext(ctx, getFlakeByAliasFingerprint, arg.Alias, arg.Fingerprint)
	var i Flake
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.LockJson,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const listFlakes = `-- name: ListFlakes :many
SELECT id, alias, flake_ref, lock_json, fingerprint, created_at FROM flakes
ORDER BY alias, id DESC
`

func (q *Queries) ListFlakes(ctx context.Context) ([]Flake, error) {
	rows, err := q.db.QueryContext(ctx, listFlakes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flake{}
	for rows.Next() {
		var i Flake
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.FlakeRef,
			&i.LockJson,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlakesByAlias = `-- name: ListFlakesByAlias :many
SELECT id, alias, flake_ref, lock_json, fingerprint, created_at FROM flakes
WHERE alias = ?
ORDER BY id DESC
`

func (q *Queries) ListFlakesByAlias(ctx context.Context, alias string) ([]Flake, error) {
	rows, err := q.db.QueryContext(ctx, listFlakesByAlias, alias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flake{}
	for rows.Next() {
		var i Flake
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.FlakeRef,
			&i.LockJson,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
