// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gc_roots.sql

package sqlc

import (
	"context"
)

const listGCRootsByProfile = `-- name: ListGCRootsByProfile :many
SELECT id, profile_id, installed_package_id, output_name, root_path, store_path, state, created_at, updated_at FROM gc_roots
WHERE profile_id = ?
ORDER BY root_path
`

func (q *Queries) ListGCRootsByProfile(ctx context.Context, profileID int64) ([]GcRoot, error) {
	rows, err := q.db.QueryContext(ctx, listGCRootsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GcRoot{}
	for rows.Next() {
		var i GcRoot
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.InstalledPackageID,
			&i.OutputName,
			&i.RootPath,
			&i.StorePath,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGCRootState = `-- name: UpdateGCRootState :one
UPDATE gc_roots
SET state = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, profile_id, installed_package_id, output_name, root_path, store_path, state, created_at, updated_at
`

type UpdateGCRootStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateGCRootState(ctx context.Context, arg UpdateGCRootStateParams) (GcRoot, error) {
	row := q.db.QueryRowContext(ctx, updateGCRootState, arg.State, arg.ID)
	var i GcRoot
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.InstalledPackageID,
		&i.OutputName,
		&i.RootPath,
		&i.StorePath,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGCRoot = `-- name: UpsertGCRoot :one
INSERT INTO gc_roots (
    profile_id,
    installed_package_id,
    output_name,
    root_path,
    store_path,
    state
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(profile_id, installed_package_id, output_name) DO UPDATE SET
    root_path = excluded.root_path,
    store_path = excluded.store_path,
    state = excluded.state,
    updated_at = unixepoch()
RETURNING id, profile_id, installed_package_id, output_name, root_path, store_path, state, created_at, updated_at
`

type UpsertGCRootParams struct {
	ProfileID          int64  `json:"profile_id"`
	InstalledPackageID int64  `json:"installed_package_id"`
	OutputName         string `json:"output_name"`
	RootPath           string `json:"root_path"`
	StorePath          string `json:"store_path"`
	State              string `json:"state"`
}

func (q *Queries) UpsertGCRoot(ctx context.Context, arg UpsertGCRootParams) (GcRoot, error) {
	row := q.db.QueryRowContext(ctx, upsertGCRoot,
		arg.ProfileID,
		arg.InstalledPackageID,
		arg.OutputName,
		arg.RootPath,
		arg.StorePath,
		arg.State,
	)
	var i GcRoot
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.InstalledPackageID,
		&i.OutputName,
		&i.RootPath,
		&i.StorePath,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
