// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installed_packages.sql

package sqlc

import (
	"context"
)

const createInstalledPackage = `-- name: CreateInstalledPackage :one
INSERT INTO installed_packages (
    profile_id,
    source_id,
    source_revision_id,
    attr,
    name,
    version,
    outputs_json,
    drv_path,
    store_paths_json,
    reason,
    priority,
    upgrade_policy,
    state
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, profile_id, source_id, source_revision_id, attr, name, version, outputs_json, drv_path, store_paths_json, reason, priority, upgrade_policy, state, created_at, updated_at
`

type CreateInstalledPackageParams struct {
	ProfileID        int64  `json:"profile_id"`
	SourceID         int64  `json:"source_id"`
	SourceRevisionID int64  `json:"source_revision_id"`
	Attr             string `json:"attr"`
	Name             string `json:"name"`
	Version          string `json:"version"`
	OutputsJson      string `json:"outputs_json"`
	DrvPath          string `json:"drv_path"`
	StorePathsJson   string `json:"store_paths_json"`
	Reason           string `json:"reason"`
	Priority         int64  `json:"priority"`
	UpgradePolicy    string `json:"upgrade_policy"`
	State            string `json:"state"`
}

func (q *Queries) CreateInstalledPackage(ctx context.Context, arg CreateInstalledPackageParams) (InstalledPackage, error) {
	row := q.db.QueryRowContext(ctx, createInstalledPackage,
		arg.ProfileID,
		arg.SourceID,
		arg.SourceRevisionID,
		arg.Attr,
		arg.Name,
		arg.Version,
		arg.OutputsJson,
		arg.DrvPath,
		arg.StorePathsJson,
		arg.Reason,
		arg.Priority,
		arg.UpgradePolicy,
		arg.State,
	)
	var i InstalledPackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.Attr,
		&i.Name,
		&i.Version,
		&i.OutputsJson,
		&i.DrvPath,
		&i.StorePathsJson,
		&i.Reason,
		&i.Priority,
		&i.UpgradePolicy,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstalledPackage = `-- name: GetInstalledPackage :one
SELECT id, profile_id, source_id, source_revision_id, attr, name, version, outputs_json, drv_path, store_paths_json, reason, priority, upgrade_policy, state, created_at, updated_at FROM installed_packages
WHERE id = ?
`

func (q *Queries) GetInstalledPackage(ctx context.Context, id int64) (InstalledPackage, error) {
	row := q.db.QueryRowContext(ctx, getInstalledPackage, id)
	var i InstalledPackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.Attr,
		&i.Name,
		&i.Version,
		&i.OutputsJson,
		&i.DrvPath,
		&i.StorePathsJson,
		&i.Reason,
		&i.Priority,
		&i.UpgradePolicy,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstalledPackagesByProfile = `-- name: ListInstalledPackagesByProfile :many
SELECT id, profile_id, source_id, source_revision_id, attr, name, version, outputs_json, drv_path, store_paths_json, reason, priority, upgrade_policy, state, created_at, updated_at FROM installed_packages
WHERE profile_id = ?
ORDER BY priority DESC, name, attr
`

func (q *Queries) ListInstalledPackagesByProfile(ctx context.Context, profileID int64) ([]InstalledPackage, error) {
	rows, err := q.db.QueryContext(ctx, listInstalledPackagesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstalledPackage{}
	for rows.Next() {
		var i InstalledPackage
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceID,
			&i.SourceRevisionID,
			&i.Attr,
			&i.Name,
			&i.Version,
			&i.OutputsJson,
			&i.DrvPath,
			&i.StorePathsJson,
			&i.Reason,
			&i.Priority,
			&i.UpgradePolicy,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstalledPackageState = `-- name: UpdateInstalledPackageState :one
UPDATE installed_packages
SET state = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, profile_id, source_id, source_revision_id, attr, name, version, outputs_json, drv_path, store_paths_json, reason, priority, upgrade_policy, state, created_at, updated_at
`

type UpdateInstalledPackageStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateInstalledPackageState(ctx context.Context, arg UpdateInstalledPackageStateParams) (InstalledPackage, error) {
	row := q.db.QueryRowContext(ctx, updateInstalledPackageState, arg.State, arg.ID)
	var i InstalledPackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceID,
		&i.SourceRevisionID,
		&i.Attr,
		&i.Name,
		&i.Version,
		&i.OutputsJson,
		&i.DrvPath,
		&i.StorePathsJson,
		&i.Reason,
		&i.Priority,
		&i.UpgradePolicy,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
