// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: licenses.sql

package sqlc

import (
	"context"
)

const getLicense = `-- name: GetLicense :one
SELECT id, open, name, description, created_at FROM licenses
WHERE id = ?
`

func (q *Queries) GetLicense(ctx context.Context, id int64) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicense, id)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Open,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLicenseByName = `-- name: GetLicenseByName :one
SELECT id, open, name, description, created_at FROM licenses
WHERE name = ?
`

func (q *Queries) GetLicenseByName(ctx context.Context, name string) (License, error) {
	row := q.db.QueryRowContext(ctx, getLicenseByName, name)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Open,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLicenses = `-- name: ListLicenses :many
SELECT id, open, name, description, created_at FROM licenses
ORDER BY name
`

func (q *Queries) ListLicenses(ctx context.Context) ([]License, error) {
	rows, err := q.db.QueryContext(ctx, listLicenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []License{}
	for rows.Next() {
		var i License
		if err := rows.Scan(
			&i.ID,
			&i.Open,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLicense = `-- name: UpsertLicense :one
INSERT INTO licenses (
    open,
    name,
    description
) VALUES (
    ?,
    ?,
    ?
)
ON CONFLICT(name) DO UPDATE SET
    open = excluded.open,
    description = excluded.description
RETURNING id, open, name, description, created_at
`

type UpsertLicenseParams struct {
	Open        int64  `json:"open"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpsertLicense(ctx context.Context, arg UpsertLicenseParams) (License, error) {
	row := q.db.QueryRowContext(ctx, upsertLicense, arg.Open, arg.Name, arg.Description)
	var i License
	err := row.Scan(
		&i.ID,
		&i.Open,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
