// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type File struct {
	ID               int64  `json:"id"`
	ProfilePackageID int64  `json:"profile_package_id"`
	Executable       int64  `json:"executable"`
	RelativePath     string `json:"relative_path"`
	MaterializedPath string `json:"materialized_path"`
	StorePath        string `json:"store_path"`
	CreatedAt        int64  `json:"created_at"`
}

type Flake struct {
	ID          int64  `json:"id"`
	Alias       string `json:"alias"`
	FlakeRef    string `json:"flake_ref"`
	LockJson    string `json:"lock_json"`
	Fingerprint string `json:"fingerprint"`
	CreatedAt   int64  `json:"created_at"`
}

type License struct {
	ID          int64  `json:"id"`
	Open        int64  `json:"open"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
}

type Package struct {
	ID          int64         `json:"id"`
	FlakeID     int64         `json:"flake_id"`
	LicenseID   sql.NullInt64 `json:"license_id"`
	Attr        string        `json:"attr"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Version     string        `json:"version"`
	Outputs     StringList    `json:"outputs"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
}

type PackagePlatform struct {
	PackageID  int64 `json:"package_id"`
	PlatformID int64 `json:"platform_id"`
}

type Platform struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type Profile struct {
	ID        int64  `json:"id"`
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Owner     string `json:"owner"`
	Path      string `json:"path"`
	CreatedAt int64  `json:"created_at"`
}

type ProfilePackage struct {
	ID         int64  `json:"id"`
	ProfileID  int64  `json:"profile_id"`
	PackageID  int64  `json:"package_id"`
	PlatformID int64  `json:"platform_id"`
	OutputName string `json:"output_name"`
	DrvPath    string `json:"drv_path"`
	StorePath  string `json:"store_path"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}
