// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (
    flake_id,
    license_id,
    attr,
    name,
    description,
    version,
    outputs
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at
`

type CreatePackageParams struct {
	FlakeID     int64         `json:"flake_id"`
	LicenseID   sql.NullInt64 `json:"license_id"`
	Attr        string        `json:"attr"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Version     string        `json:"version"`
	Outputs     StringList    `json:"outputs"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.FlakeID,
		arg.LicenseID,
		arg.Attr,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Outputs,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackage = `-- name: GetPackage :one
SELECT id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE id = ?
`

func (q *Queries) GetPackage(ctx context.Context, id int64) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageByFlakeAttr = `-- name: GetPackageByFlakeAttr :one
SELECT id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE flake_id = ? AND attr = ?
`

type GetPackageByFlakeAttrParams struct {
	FlakeID int64  `json:"flake_id"`
	Attr    string `json:"attr"`
}

func (q *Queries) GetPackageByFlakeAttr(ctx context.Context, arg GetPackageByFlakeAttrParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByFlakeAttr, arg.FlakeID, arg.Attr)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackagesByFlake = `-- name: ListPackagesByFlake :many
SELECT id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE flake_id = ?
ORDER BY attr
`

func (q *Queries) ListPackagesByFlake(ctx context.Context, flakeID int64) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByFlake, flakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.FlakeID,
			&i.LicenseID,
			&i.Attr,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Outputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPackagesByName = `-- name: SearchPackagesByName :many
SELECT id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE name LIKE ? OR attr LIKE ?
ORDER BY name, attr
LIMIT ?
`

type SearchPackagesByNameParams struct {
	Name  string `json:"name"`
	Attr  string `json:"attr"`
	Limit int64  `json:"limit"`
}

func (q *Queries) SearchPackagesByName(ctx context.Context, arg SearchPackagesByNameParams) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, searchPackagesByName, arg.Name, arg.Attr, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.FlakeID,
			&i.LicenseID,
			&i.Attr,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Outputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageMetadata = `-- name: UpdatePackageMetadata :one
UPDATE packages
SET license_id = ?,
    name = ?,
    description = ?,
    version = ?,
    outputs = ?,
    updated_at = unixepoch()
WHERE id = ?
RETURNING id, flake_id, license_id, attr, name, description, version, outputs, created_at, updated_at
`

type UpdatePackageMetadataParams struct {
	LicenseID   sql.NullInt64 `json:"license_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Version     string        `json:"version"`
	Outputs     StringList    `json:"outputs"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdatePackageMetadata(ctx context.Context, arg UpdatePackageMetadataParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, updatePackageMetadata,
		arg.LicenseID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Outputs,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
