// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (
    flake_revision_id,
    license_id,
    attr,
    name,
    description,
    version,
    outputs
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at
`

type CreatePackageParams struct {
	FlakeRevisionID int64         `json:"flake_revision_id"`
	LicenseID       sql.NullInt64 `json:"license_id"`
	Attr            string        `json:"attr"`
	Name            string        `json:"name"`
	Description     string        `json:"description"`
	Version         string        `json:"version"`
	Outputs         StringList    `json:"outputs"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, createPackage,
		arg.FlakeRevisionID,
		arg.LicenseID,
		arg.Attr,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Outputs,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeRevisionID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPackageByFlakeAlias = `-- name: GetLatestPackageByFlakeAlias :one
SELECT packages.id, packages.flake_revision_id, packages.license_id, packages.attr, packages.name, packages.description, packages.version, packages.outputs, packages.created_at, packages.updated_at FROM packages
JOIN flake_revisions ON flake_revisions.id = packages.flake_revision_id
JOIN flakes ON flakes.id = flake_revisions.flake_id
WHERE flakes.owner = ?
  AND flakes.alias = ?
  AND packages.attr = ?
ORDER BY flake_revisions.created_at DESC, flake_revisions.id DESC
LIMIT 1
`

type GetLatestPackageByFlakeAliasParams struct {
	Owner string `json:"owner"`
	Alias string `json:"alias"`
	Attr  string `json:"attr"`
}

func (q *Queries) GetLatestPackageByFlakeAlias(ctx context.Context, arg GetLatestPackageByFlakeAliasParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getLatestPackageByFlakeAlias, arg.Owner, arg.Alias, arg.Attr)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeRevisionID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackage = `-- name: GetPackage :one
SELECT id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE id = ?
`

func (q *Queries) GetPackage(ctx context.Context, id int64) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackage, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeRevisionID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageByRevisionAttr = `-- name: GetPackageByRevisionAttr :one
SELECT id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE flake_revision_id = ? AND attr = ?
`

type GetPackageByRevisionAttrParams struct {
	FlakeRevisionID int64  `json:"flake_revision_id"`
	Attr            string `json:"attr"`
}

func (q *Queries) GetPackageByRevisionAttr(ctx context.Context, arg GetPackageByRevisionAttrParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByRevisionAttr, arg.FlakeRevisionID, arg.Attr)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeRevisionID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackagesByRevision = `-- name: ListPackagesByRevision :many
SELECT id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE flake_revision_id = ?
ORDER BY attr
`

func (q *Queries) ListPackagesByRevision(ctx context.Context, flakeRevisionID int64) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByRevision, flakeRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.FlakeRevisionID,
			&i.LicenseID,
			&i.Attr,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Outputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPackagesByName = `-- name: SearchPackagesByName :many
SELECT id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at FROM packages
WHERE name LIKE ? OR attr LIKE ?
ORDER BY name, attr
LIMIT ?
`

type SearchPackagesByNameParams struct {
	Name  string `json:"name"`
	Attr  string `json:"attr"`
	Limit int64  `json:"limit"`
}

func (q *Queries) SearchPackagesByName(ctx context.Context, arg SearchPackagesByNameParams) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, searchPackagesByName, arg.Name, arg.Attr, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.FlakeRevisionID,
			&i.LicenseID,
			&i.Attr,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Outputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageMetadata = `-- name: UpdatePackageMetadata :one
UPDATE packages
SET license_id = ?,
    name = ?,
    description = ?,
    version = ?,
    outputs = ?,
    updated_at = unixepoch()
WHERE id = ?
RETURNING id, flake_revision_id, license_id, attr, name, description, version, outputs, created_at, updated_at
`

type UpdatePackageMetadataParams struct {
	LicenseID   sql.NullInt64 `json:"license_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Version     string        `json:"version"`
	Outputs     StringList    `json:"outputs"`
	ID          int64         `json:"id"`
}

func (q *Queries) UpdatePackageMetadata(ctx context.Context, arg UpdatePackageMetadataParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, updatePackageMetadata,
		arg.LicenseID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Outputs,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.FlakeRevisionID,
		&i.LicenseID,
		&i.Attr,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Outputs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
