// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: package_platforms.sql

package sqlc

import (
	"context"
)

const linkPackagePlatform = `-- name: LinkPackagePlatform :exec
INSERT OR IGNORE INTO package_platforms (
    package_id,
    platform_id
) VALUES (
    ?,
    ?
)
`

type LinkPackagePlatformParams struct {
	PackageID  int64 `json:"package_id"`
	PlatformID int64 `json:"platform_id"`
}

func (q *Queries) LinkPackagePlatform(ctx context.Context, arg LinkPackagePlatformParams) error {
	_, err := q.db.ExecContext(ctx, linkPackagePlatform, arg.PackageID, arg.PlatformID)
	return err
}

const listPackagePlatforms = `-- name: ListPackagePlatforms :many
SELECT platforms.id, platforms.name, platforms.created_at FROM platforms
JOIN package_platforms ON package_platforms.platform_id = platforms.id
WHERE package_platforms.package_id = ?
ORDER BY platforms.name
`

func (q *Queries) ListPackagePlatforms(ctx context.Context, packageID int64) ([]Platform, error) {
	rows, err := q.db.QueryContext(ctx, listPackagePlatforms, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Platform{}
	for rows.Next() {
		var i Platform
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByPlatform = `-- name: ListPackagesByPlatform :many
SELECT packages.id, packages.flake_revision_id, packages.license_id, packages.attr, packages.name, packages.description, packages.version, packages.outputs, packages.created_at, packages.updated_at FROM packages
JOIN package_platforms ON package_platforms.package_id = packages.id
WHERE package_platforms.platform_id = ?
ORDER BY packages.name, packages.attr
`

func (q *Queries) ListPackagesByPlatform(ctx context.Context, platformID int64) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByPlatform, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.FlakeRevisionID,
			&i.LicenseID,
			&i.Attr,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Outputs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
