// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platforms.sql

package sqlc

import (
	"context"
)

const getPlatform = `-- name: GetPlatform :one
SELECT id, name, created_at FROM platforms
WHERE id = ?
`

func (q *Queries) GetPlatform(ctx context.Context, id int64) (Platform, error) {
	row := q.db.QueryRowContext(ctx, getPlatform, id)
	var i Platform
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPlatformByName = `-- name: GetPlatformByName :one
SELECT id, name, created_at FROM platforms
WHERE name = ?
`

func (q *Queries) GetPlatformByName(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRowContext(ctx, getPlatformByName, name)
	var i Platform
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listPlatforms = `-- name: ListPlatforms :many
SELECT id, name, created_at FROM platforms
ORDER BY name
`

func (q *Queries) ListPlatforms(ctx context.Context) ([]Platform, error) {
	rows, err := q.db.QueryContext(ctx, listPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Platform{}
	for rows.Next() {
		var i Platform
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlatform = `-- name: UpsertPlatform :one
INSERT INTO platforms (
    name
) VALUES (
    ?
)
ON CONFLICT(name) DO UPDATE SET
    name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertPlatform(ctx context.Context, name string) (Platform, error) {
	row := q.db.QueryRowContext(ctx, upsertPlatform, name)
	var i Platform
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
