// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_packages.sql

package sqlc

import (
	"context"
)

const createProfilePackage = `-- name: CreateProfilePackage :one
INSERT INTO profile_packages (
    profile_id,
    package_id,
    platform_id,
    output_name,
    drv_path,
    store_path
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(package_id, profile_id, output_name, platform_id) DO UPDATE SET
    drv_path = excluded.drv_path,
    store_path = excluded.store_path,
    updated_at = unixepoch()
RETURNING id, profile_id, package_id, platform_id, output_name, drv_path, store_path, created_at, updated_at
`

type CreateProfilePackageParams struct {
	ProfileID  int64  `json:"profile_id"`
	PackageID  int64  `json:"package_id"`
	PlatformID int64  `json:"platform_id"`
	OutputName string `json:"output_name"`
	DrvPath    string `json:"drv_path"`
	StorePath  string `json:"store_path"`
}

func (q *Queries) CreateProfilePackage(ctx context.Context, arg CreateProfilePackageParams) (ProfilePackage, error) {
	row := q.db.QueryRowContext(ctx, createProfilePackage,
		arg.ProfileID,
		arg.PackageID,
		arg.PlatformID,
		arg.OutputName,
		arg.DrvPath,
		arg.StorePath,
	)
	var i ProfilePackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PackageID,
		&i.PlatformID,
		&i.OutputName,
		&i.DrvPath,
		&i.StorePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfilePackage = `-- name: DeleteProfilePackage :exec
DELETE FROM profile_packages
WHERE id = ?
`

func (q *Queries) DeleteProfilePackage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProfilePackage, id)
	return err
}

const getProfilePackage = `-- name: GetProfilePackage :one
SELECT id, profile_id, package_id, platform_id, output_name, drv_path, store_path, created_at, updated_at FROM profile_packages
WHERE id = ?
`

func (q *Queries) GetProfilePackage(ctx context.Context, id int64) (ProfilePackage, error) {
	row := q.db.QueryRowContext(ctx, getProfilePackage, id)
	var i ProfilePackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PackageID,
		&i.PlatformID,
		&i.OutputName,
		&i.DrvPath,
		&i.StorePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfilePackageByOutput = `-- name: GetProfilePackageByOutput :one
SELECT id, profile_id, package_id, platform_id, output_name, drv_path, store_path, created_at, updated_at FROM profile_packages
WHERE profile_id = ?
  AND package_id = ?
  AND platform_id = ?
  AND output_name = ?
`

type GetProfilePackageByOutputParams struct {
	ProfileID  int64  `json:"profile_id"`
	PackageID  int64  `json:"package_id"`
	PlatformID int64  `json:"platform_id"`
	OutputName string `json:"output_name"`
}

func (q *Queries) GetProfilePackageByOutput(ctx context.Context, arg GetProfilePackageByOutputParams) (ProfilePackage, error) {
	row := q.db.QueryRowContext(ctx, getProfilePackageByOutput,
		arg.ProfileID,
		arg.PackageID,
		arg.PlatformID,
		arg.OutputName,
	)
	var i ProfilePackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PackageID,
		&i.PlatformID,
		&i.OutputName,
		&i.DrvPath,
		&i.StorePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfilePackages = `-- name: ListProfilePackages :many
SELECT id, profile_id, package_id, platform_id, output_name, drv_path, store_path, created_at, updated_at FROM profile_packages
WHERE profile_id = ?
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListProfilePackages(ctx context.Context, profileID int64) ([]ProfilePackage, error) {
	rows, err := q.db.QueryContext(ctx, listProfilePackages, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilePackage{}
	for rows.Next() {
		var i ProfilePackage
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.PackageID,
			&i.PlatformID,
			&i.OutputName,
			&i.DrvPath,
			&i.StorePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchProfilePackage = `-- name: TouchProfilePackage :one
UPDATE profile_packages
SET updated_at = unixepoch()
WHERE id = ?
RETURNING id, profile_id, package_id, platform_id, output_name, drv_path, store_path, created_at, updated_at
`

func (q *Queries) TouchProfilePackage(ctx context.Context, id int64) (ProfilePackage, error) {
	row := q.db.QueryRowContext(ctx, touchProfilePackage, id)
	var i ProfilePackage
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PackageID,
		&i.PlatformID,
		&i.OutputName,
		&i.DrvPath,
		&i.StorePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
