// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    kind,
    name,
    path,
    active_revision
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, kind, name, path, active_revision, created_at
`

type CreateProfileParams struct {
	Kind           string `json:"kind"`
	Name           string `json:"name"`
	Path           string `json:"path"`
	ActiveRevision string `json:"active_revision"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Kind,
		arg.Name,
		arg.Path,
		arg.ActiveRevision,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ActiveRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, kind, name, path, active_revision, created_at FROM profiles
WHERE id = ?
`

func (q *Queries) GetProfile(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ActiveRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByKindName = `-- name: GetProfileByKindName :one
SELECT id, kind, name, path, active_revision, created_at FROM profiles
WHERE kind = ? AND name = ?
`

type GetProfileByKindNameParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

func (q *Queries) GetProfileByKindName(ctx context.Context, arg GetProfileByKindNameParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByKindName, arg.Kind, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ActiveRevision,
		&i.CreatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, kind, name, path, active_revision, created_at FROM profiles
ORDER BY kind, name
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Path,
			&i.ActiveRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileActiveRevision = `-- name: UpdateProfileActiveRevision :one
UPDATE profiles
SET active_revision = ?
WHERE id = ?
RETURNING id, kind, name, path, active_revision, created_at
`

type UpdateProfileActiveRevisionParams struct {
	ActiveRevision string `json:"active_revision"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateProfileActiveRevision(ctx context.Context, arg UpdateProfileActiveRevisionParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileActiveRevision, arg.ActiveRevision, arg.ID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Path,
		&i.ActiveRevision,
		&i.CreatedAt,
	)
	return i, err
}
