// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (
    alias,
    flake_ref,
    enabled,
    priority
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, alias, flake_ref, enabled, priority, current_revision_id, created_at
`

type CreateSourceParams struct {
	Alias    string `json:"alias"`
	FlakeRef string `json:"flake_ref"`
	Enabled  int64  `json:"enabled"`
	Priority int64  `json:"priority"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.Alias,
		arg.FlakeRef,
		arg.Enabled,
		arg.Priority,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.Enabled,
		&i.Priority,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const createSourceRevision = `-- name: CreateSourceRevision :one
INSERT INTO source_revisions (
    source_id,
    lock_json,
    fingerprint,
    metadata_json
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, source_id, lock_json, fingerprint, metadata_json, created_at
`

type CreateSourceRevisionParams struct {
	SourceID     int64  `json:"source_id"`
	LockJson     string `json:"lock_json"`
	Fingerprint  string `json:"fingerprint"`
	MetadataJson string `json:"metadata_json"`
}

func (q *Queries) CreateSourceRevision(ctx context.Context, arg CreateSourceRevisionParams) (SourceRevision, error) {
	row := q.db.QueryRowContext(ctx, createSourceRevision,
		arg.SourceID,
		arg.LockJson,
		arg.Fingerprint,
		arg.MetadataJson,
	)
	var i SourceRevision
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.LockJson,
		&i.Fingerprint,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentSourceRevisionByAlias = `-- name: GetCurrentSourceRevisionByAlias :one
SELECT source_revisions.id, source_revisions.source_id, source_revisions.lock_json, source_revisions.fingerprint, source_revisions.metadata_json, source_revisions.created_at FROM source_revisions
JOIN sources ON sources.current_revision_id = source_revisions.id
WHERE sources.alias = ?
`

func (q *Queries) GetCurrentSourceRevisionByAlias(ctx context.Context, alias string) (SourceRevision, error) {
	row := q.db.QueryRowContext(ctx, getCurrentSourceRevisionByAlias, alias)
	var i SourceRevision
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.LockJson,
		&i.Fingerprint,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, alias, flake_ref, enabled, priority, current_revision_id, created_at FROM sources
WHERE id = ?
`

func (q *Queries) GetSource(ctx context.Context, id int64) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.Enabled,
		&i.Priority,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceByAlias = `-- name: GetSourceByAlias :one
SELECT id, alias, flake_ref, enabled, priority, current_revision_id, created_at FROM sources
WHERE alias = ?
`

func (q *Queries) GetSourceByAlias(ctx context.Context, alias string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByAlias, alias)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.Enabled,
		&i.Priority,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceRevision = `-- name: GetSourceRevision :one
SELECT id, source_id, lock_json, fingerprint, metadata_json, created_at FROM source_revisions
WHERE id = ?
`

func (q *Queries) GetSourceRevision(ctx context.Context, id int64) (SourceRevision, error) {
	row := q.db.QueryRowContext(ctx, getSourceRevision, id)
	var i SourceRevision
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.LockJson,
		&i.Fingerprint,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listSourceRevisions = `-- name: ListSourceRevisions :many
SELECT id, source_id, lock_json, fingerprint, metadata_json, created_at FROM source_revisions
WHERE source_id = ?
ORDER BY id DESC
`

func (q *Queries) ListSourceRevisions(ctx context.Context, sourceID int64) ([]SourceRevision, error) {
	rows, err := q.db.QueryContext(ctx, listSourceRevisions, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceRevision{}
	for rows.Next() {
		var i SourceRevision
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.LockJson,
			&i.Fingerprint,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, alias, flake_ref, enabled, priority, current_revision_id, created_at FROM sources
ORDER BY priority DESC, alias
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.FlakeRef,
			&i.Enabled,
			&i.Priority,
			&i.CurrentRevisionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceCurrentRevision = `-- name: SetSourceCurrentRevision :one
UPDATE sources
SET current_revision_id = ?
WHERE id = ?
RETURNING id, alias, flake_ref, enabled, priority, current_revision_id, created_at
`

type SetSourceCurrentRevisionParams struct {
	CurrentRevisionID sql.NullInt64 `json:"current_revision_id"`
	ID                int64         `json:"id"`
}

func (q *Queries) SetSourceCurrentRevision(ctx context.Context, arg SetSourceCurrentRevisionParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, setSourceCurrentRevision, arg.CurrentRevisionID, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.FlakeRef,
		&i.Enabled,
		&i.Priority,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}
