// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addTransactionItem = `-- name: AddTransactionItem :one
INSERT INTO transaction_items (
    transaction_id,
    action,
    package_id,
    old_json,
    new_json,
    state,
    error
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, transaction_id, "action", package_id, old_json, new_json, state, error
`

type AddTransactionItemParams struct {
	TransactionID int64         `json:"transaction_id"`
	Action        string        `json:"action"`
	PackageID     sql.NullInt64 `json:"package_id"`
	OldJson       string        `json:"old_json"`
	NewJson       string        `json:"new_json"`
	State         string        `json:"state"`
	Error         string        `json:"error"`
}

func (q *Queries) AddTransactionItem(ctx context.Context, arg AddTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRowContext(ctx, addTransactionItem,
		arg.TransactionID,
		arg.Action,
		arg.PackageID,
		arg.OldJson,
		arg.NewJson,
		arg.State,
		arg.Error,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Action,
		&i.PackageID,
		&i.OldJson,
		&i.NewJson,
		&i.State,
		&i.Error,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    kind,
    profile_id,
    state,
    metadata_json
) VALUES (
    ?,
    ?,
    ?,
    ?
) RETURNING id, kind, profile_id, state, started_at, finished_at, error, metadata_json
`

type CreateTransactionParams struct {
	Kind         string        `json:"kind"`
	ProfileID    sql.NullInt64 `json:"profile_id"`
	State        string        `json:"state"`
	MetadataJson string        `json:"metadata_json"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Kind,
		arg.ProfileID,
		arg.State,
		arg.MetadataJson,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProfileID,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.MetadataJson,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, kind, profile_id, state, started_at, finished_at, error, metadata_json FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProfileID,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.MetadataJson,
	)
	return i, err
}

const listUnfinishedTransactions = `-- name: ListUnfinishedTransactions :many
SELECT id, kind, profile_id, state, started_at, finished_at, error, metadata_json FROM transactions
WHERE state NOT IN ('succeeded', 'failed', 'interrupted')
ORDER BY id
`

func (q *Queries) ListUnfinishedTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProfileID,
			&i.State,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionItemState = `-- name: UpdateTransactionItemState :one
UPDATE transaction_items
SET state = ?,
    error = ?
WHERE id = ?
RETURNING id, transaction_id, "action", package_id, old_json, new_json, state, error
`

type UpdateTransactionItemStateParams struct {
	State string `json:"state"`
	Error string `json:"error"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateTransactionItemState(ctx context.Context, arg UpdateTransactionItemStateParams) (TransactionItem, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionItemState, arg.State, arg.Error, arg.ID)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Action,
		&i.PackageID,
		&i.OldJson,
		&i.NewJson,
		&i.State,
		&i.Error,
	)
	return i, err
}

const updateTransactionState = `-- name: UpdateTransactionState :one
UPDATE transactions
SET state = ?,
    finished_at = ?,
    error = ?
WHERE id = ?
RETURNING id, kind, profile_id, state, started_at, finished_at, error, metadata_json
`

type UpdateTransactionStateParams struct {
	State      string        `json:"state"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	Error      string        `json:"error"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionState,
		arg.State,
		arg.FinishedAt,
		arg.Error,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProfileID,
		&i.State,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.MetadataJson,
	)
	return i, err
}
